# -*- coding: utf-8 -*-
# AUTO-GENERATED by _build_prie_early.py (merged increments). `prie-` words whose se8-fall arms
# EARLY (prefix-stressed): the arm goes to the syllable-1 `-ie` offglide START. Verified: that
# arm reproduces the engine WAV bit-exactly. Words NOT here keep the default (later) arm.
PRIE_EARLY = {'priedėlis', 'priemonė', 'priekalas', 'prielanka', 'priežodis', 'priemaina', 'prielipa', 'priemiega', 'priemokos', 'priesienė', 'priebutis', 'priežiūrą', 'priekabę', 'priesakas', 'priežiūra', 'priemonei', 'priebradė', 'priemoka', 'priekabos', 'priekaba', 'priegaida', 'priemonės', 'priedanga', 'priesaika', 'priekabus', 'priekabė', 'prievolės', 'prievolė'}
